
name: "Deploy to Server"

on:
  push:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}

    steps:
      - uses: actions/checkout@v3

      - name: "Build Docker Image"
        run: |
          docker login -u riyazmanandhar -p $DOCKERHUB_PAT
          docker build -t riyazmanandhar/semester3 .
          docker push riyazmanandhar/semester3
        env:
          DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}

      - name: "Configure SSH"
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      
      - name: "Put SSH Key in Docker file for Server Access"
        run: |
          touch pem.pem
          echo $SSH_KEY64 | base64 -d > pem.pem && chmod 400 pem.pem
          ssh-keygen -R $SERVER_IP
        env: 
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}

      - name: "Docker Pull and Restart Docker"
        run: |
          ssh -t ubuntu@$SERVER_IP -i pem.pem 'docker pull riyazmanandhar/semester3'
          ssh -t ubuntu@$SERVER_IP -i pem.pem 'docker stop nginx33 || true && docker rm nginx33 || true'

          ssh -t ubuntu@$SERVER_IP -i pem.pem 'docker run --name nginx33 -p 80:80 -d riyazmanandhar/semester3'
